# 标准合法的 hugo.toml 配置（适配你的需求）
baseURL = 'https://muzhui.cn/'
title = 'COST ✕ JUNYAO'
languageCode = 'zh-cn'
canonifyURLs = false
disablePathToLower = false

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'POST'
pageRef = '/posts/'
weight = 20

[[menus.main]]
name = 'ABOUT'
pageRef = '/about/'
weight = 30

[module]
  [[module.mounts]]
    source = 'themes/freshpink/layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'themes/freshpink/assets'
    target = 'assets'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'themes/freshpink/static'
    target = 'static'
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = 'static'
    target = 'static'

[params]
copyright = 'Copyright © 2024 COST ✕ JUNYAO'
primaryColor = "#000000"
math = true
githubUsername = "yourGithubUsername"
showGithubChart = true
mainImageUrl = "img/shouye.png"
showMainImage = true

[author]
name = "Jun Yao"
homepage = "https://muzhui.cn/"

[taxonomies]
category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3

[pagination]
  paginate = 10
  paginatePath = "page"