baseURL = "https://muzhui.cn/"
languageCode = "en-us"
title = "槌"
theme = "yinyang"
DefaultContentLanguage = "cn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "王君尧"
  homepage = "https://muzhui.cn/"


[params]
mainSections = ["posts"]
headTitle = "muzhu"
favicon = "/favicon.ico"
[[params.socials]]
name = "文章"
link = "/posts/"

[[params.socials]]
name = "装备"
link = "/equipment/"

[[params.socials]]
name = "关于"
link = "/about/"


# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []